# Generated by Django 2.2.2 on 2019-07-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='orders',
            field=models.TextField(default='0', max_length=500),
        ),
    ]
