# Generated by Django 2.2.2 on 2019-07-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20190726_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='orders',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
